services:
  embedding-api:
    build: .
    container_name: embedding-api
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./cache/:/app/cache
    networks:
      - pdm-network

networks:
  pdm-network:
    driver: bridge
    name: pdm-network